### ISSUE TITLE
Создание и редактирование сотрудника: Уточнить ограничение на алфавиты на ввод в поле "Отчество"

### ISSUE THREAD

**Issue by vitalik98** [vliplianina/scrum-team-9a#142]

**Comment by vliplianina** [comment]
Некорректная формулировка "алфавиты на ввод".
Будет точнее сформулировать как "уточнить ограничения на ввод значений определённых алфавитов" или "уточнить, буквы каких алфавитов допустимы".

Для поля "Отчество" допустим ввод кириллицы и латиницы. Ограничения добавлены в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п.3.7. "Форма ввода персоны (исполнителя)"
