### ISSUE TITLE
Создание и редактирование задачи: Уточнить, что произойдет, при вводе некорректных данных в поле "Отчество"

### ISSUE THREAD

**Issue by vitalik98** [vliplianina/scrum-team-9a#149]

**Comment by vliplianina** [comment]
Для формы редактирования сотрудника уточнение требований в issue #154.
Прошу отредактировать заголовок.

**Comment by vliplianina** [comment]
Запрета на ввод нет, но при попытке сохранения невалидных данных появится сообщение об ошибке
