### ISSUE TITLE
Создание и редактирование задачи: Уточнить, что произойдет, если оставить поле "Отчество" пустым

### ISSUE THREAD

**Issue by vitalik98** [vliplianina/scrum-team-9a#154]

**Comment by vliplianina** [comment]
Если оставить пустым, заполнить остальные поля и нажать кнопку "Сохранить", то появится валидационное сообщение о необходимости заполнения обязательного поля

**Comment by vliplianina** [comment]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п.3.7
