### ISSUE TITLE
Форма создания/редактирования проекта: Уточнить допустимость специального символа "пробел" в графе "Описание"

### ISSUE THREAD

**Issue by AndrewMirugin** [vliplianina/scrum-team-9a#159]

**Comment by vliplianina** [comment]
Пробел допустим. Дефект требований.
Исправлено см. [п. 3.5. "Форма ввода проекта"](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md)
