### ISSUE TITLE
Создание и редактирование задачи: Уточнить логические ограничения на ввод в поле "Название"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#16]

**Comment by vliplianina** [comment]
Допустимые символы для поля "Название"
латиница [A-z], кириллица [А-я], цифры [0-9], точка [.], запятая [,], точка с запятой [;], двоеточие [:], дефис [-], апостроф ['], слеш [/], процент [%], амперсанд [&], нижнее подчеркивание [ _ ]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
