### ISSUE TITLE
Удаление проекта: уточнить что происходит при удалении последней записи в таблице

### ISSUE THREAD

**Issue by vkapsky** [vliplianina/scrum-team-9a#17]

**Comment by vliplianina** [comment]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md). 
См. п. 4."Приложение должно обрабатывать следующие условия" > пп. 4.1. "Список проектов / задач / сотрудников"
