### ISSUE TITLE
Создание и редактирование задачи: Уточнить логические ограничения на ввод в поле "Дата начала"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#25]

**Comment by vliplianina** [comment]
Допустимый диапазон [01-01-1990;31-12-2099]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
