### ISSUE TITLE
Проект: уточнить поддерживаемые спецсимволы на ввод в поле "Описание" 

### ISSUE THREAD

**Issue by AndrewMirugin** [vliplianina/scrum-team-9a#29]

**Comment by vliplianina** [comment]
Допустимы следующие спец.символы: точка [.], дефис [-], апостроф ['], слеш [/], нижнее подчеркивание [ _ ], вопрос [?]
Лучше вопросы на ввод допустимых символов объединять в один, чтобы сразу узнать про буквы, цифры, спец.символы (в т.ч. пробел)
Обновлено в [требованиях](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п.3.5. Форма ввода проекта.
