### ISSUE TITLE
Удаление задачи: Уточнить что произойдет после удаления единственной задачи из таблицы

### ISSUE THREAD

**Issue by VeronikaBogdanovich** [vliplianina/scrum-team-9a#3]

**Comment by vliplianina** [comment]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md). 
См. п. 4."Приложение должно обрабатывать следующие условия" > пп. 4.1. "Список проектов / задач / сотрудников"
