### ISSUE TITLE
Создание и редактирование задачи: Уточнить физические ограничения на ввод в поле "Название"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#4]
При создании и редоктировании формы

**Comment by vliplianina** [comment]
[2-255] символов. 
Обновлено в [требованиях](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п.3.6.	Форма ввода задачи

**Comment by vliplianina** [comment]
@annametelskaya исправьте в описании опечатку и укажите верное название формы.
