### ISSUE TITLE
Создание и редактирование задачи: Уточнить  поддержку на ввод цифр в поле "Дата начала"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#41]

**Comment by vliplianina** [comment]
Неполный или некорректный запрос на уточнение. Для ввода даты используются цифры и спец.символы. Формат ввода и допустимый диапазон см. в [требованиях](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
