### ISSUE TITLE
Создание и редактирование задачи: Уточнить, что произойдет, если ничего не написать в поле "Работа"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#46]

**Comment by vliplianina** [comment]
Отобразится сообщение об ошибке, т.к. поле является обязательным

**Comment by vliplianina** [comment]
Отобразится сообщение об ошибке, т.к. поле обязательно для заполнения.

Замечание: глагол "написать" следует заменить на технический термин вида "ввести" или перефразировать "заполнить поле"
