### ISSUE TITLE
Создание и редактирование задачи: Уточнить, что произойдет, если ничего не выбрать в поле "Статус"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#49]

**Comment by vliplianina** [comment]
Отобразится сообщение об ошибке, т.к. поле является обязательным.
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
