### ISSUE TITLE
Создание и редактирование задачи: Уточнить, что произойдет, когда дата указанная в поле "Дата окончания" будет раньше, чем дата в поле "Дата окончания"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#51]

**Comment by vliplianina** [comment]
Отобразится сообщение об ошибке, т.к. дата окончания не может быть меньше даты начала.
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
