### ISSUE TITLE
Создание и редактирование задачи: Уточнить поддержку на ввод цифр в поле "Работа"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#61]

**Comment by vliplianina** [comment]
Цифры допустимы

**Comment by vliplianina** [comment]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
