### ISSUE TITLE
Создание и редактирование задачи: Уточнить поддерживаемые спецсимволы на ввод в поле "Название"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#62]

**Comment by vliplianina** [comment]
Точка [.], запятая [,], точка с запятой [;], двоеточие [:], дефис [-], апостроф ['], слеш [/], процент [%], амперсанд [&], нижнее подчеркивание [ _ ]
Уточнение добавлено в [требования](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п. 3.6. "Форма ввода задачи"
