### ISSUE TITLE
Создание и редактирование задачи: Уточнить физические ограничения на ввод в поле "Дата начала"

### ISSUE THREAD

**Issue by annametelskaya** [vliplianina/scrum-team-9a#7]

**Comment by vliplianina** [comment]
Поля "Дата начала" и "Дата окончания" должны быть ограничено маской формата ДД-ММ-ГГГГ
Обновлено в [требованиях](https://github.com/vliplianina/scrum-team-9a/blob/master/TrainingTask%20-%20Requirements.md) п.3.6. Форма ввода задачи.
